version: "3.8"
services:
  dev_app:
    build: .
    volumes:
      - .:/app
    ports:
      - 5001:5000
    command: bash -c "flask run --host=0.0.0.0"
    environment:
      - FLASK_APP=main
      - FLASK_DEBUG=on
      - FLASK_ENV=development
      - TZ=Asia/Tokyo
  test_app:
    build: .
    volumes:
      - .:/app
    command: bash -c "flask run --host=0.0.0.0"
    environment:
      - FLASK_APP=main
      - FLASK_DEBUG=on
      - FLASK_ENV=test
      - TZ=Asia/Tokyo
  postgres:
    image: postgres:16.2-bookworm
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TZ=Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d
